### ISSUE TITLE
Get an error: Class properties must be methods

### ISSUE THREAD

**Issue by langdonx** [wcandillon/swagger-js-codegen#109]
test.js created from by pasting the Example from `README.md`:

	$ node test.js
	xxx\node_modules\swagger-js-codegen\lib\codegen.js:231
			throw new Error(error.reason + ' in ' + error.evidence + ' ('
			      ^
	Error: Class properties must be methods. Expected '(' but instead saw 'domain'. in     private domain: string; (E054)
	    at xxx\node_modules\swagger-js-codegen\lib\codegen.js:231:23
	    at Array.forEach (native)
	    at getCode (xxx\node_modules\swagger-js-codegen\lib\codegen.js:229:21)
	    at Object.exports.CodeGen.getTypescriptCode (xxx\node_modules\swagger-js-codegen\lib\codegen.js:247:16)
	    at Object.<anonymous> (xxx\test.js:8:28)
	    at Module._compile (module.js:460:26)
	    at Object.Module._extensions..js (module.js:478:10)
	    at Module.load (module.js:355:32)
	    at Function.Module._load (module.js:310:12)
	    at Function.Module.runMain (module.js:501:10)

Not really sure where to start looking.  The word "domain" isn't used in my spec file.

ETA: It looks like it fails linting... when I paste my spec into www.jshint.com, it doesn't produce any errors.  Oh, I guess it lints what it generates.  Ignoring the errors now to see what the result is.

**Comment by langdonx** [comment]
It's a bug in the template:

https://github.com/wcandillon/swagger-js-codegen/blob/master/templates/angular-class.mustache#L18

The declaration of `domain` needs to be moved to line 17.  I'm guessing not a lot of folks use this for Angular 1? :wink:

**Comment by pixelshaded** [comment]
getting the same error when trying to generate typescript.

**Comment by langdonx** [comment]
FYI, @wcandillon that fix will still generate bad code for JavaScript  `angular-class.mustache` has a bug in it (line 31+39 are referencing `domain` when they should be referencing `this.domain`.

**Comment by wcandillon** [comment]
@langdonx can you try in v1.3.3 to check if this is fixed?

**Comment by langdonx** [comment]
Ahh, it does look fixed, sorry!  Threw me off that the change wasn't associated w/ the issue.

**Comment by wcandillon** [comment]
yes sorry it was my mistake
