### ISSUE TITLE
Explicitly specify Content-Type

### ISSUE THREAD

**Issue by chdanielmueller** [wcandillon/swagger-js-codegen#119]
If the content type is either specified in the operation or as overall "consumes" property it should be added as header.
I got problems with this as my API checks for the Content-Type property.

**Comment by PizzaPete** [comment]
I've fixed this for the 'produces' property a [week ago](https://github.com/wcandillon/swagger-js-codegen/issues/113).
Might help you in fixing it for the 'consumes' property.

**Comment by chdanielmueller** [comment]
I already opened a pull request #120 which would solve this issue.
(And took your code as example :wink:)
