### ISSUE TITLE
Breaking commit should be major version change.

### ISSUE THREAD

**Issue by PepijnSenders** [wcandillon/swagger-js-codegen#136]
Hey @wcandillon, this commit: https://github.com/wcandillon/swagger-js-codegen/commit/f0817cd60775efc6f480d066334f06a22e36200a#diff-3e068a9eceaa0cfe1edb512730c5f6b9 broke our live environment, since it change all our parameter names to `camelCase` instead of `snake_case`. These kind of changes are supposed to major changes in your version number. So 1.7.0 would have matches this better.

Please watch out better next time 🔥

**Comment by wcandillon** [comment]
@PepijnSenders My apologies for this 🙏
