### ISSUE TITLE
How to use typescript generation

### ISSUE THREAD

**Issue by no-more** [wcandillon/swagger-js-codegen#139]
Hello,

I'm trying to use typescript generation, but I'm not sure how to do it. Could someone give me more information about : 
- The imports property, what is it for ? `CodeGen.getTypescriptCode({ className: 'Test', swagger: swagger, imports: ['../../typings/tsd.d.ts'] });`
- Is it required? it seems to work without?
- Is there any way to generate the models automatically ?
- I'm using hapi-swagger and when models are not explicitly named I have name like : "Model 2" or "Model 6" which is badly handled by the code generation process like this one :
  `parameters: {
      'body' ? : Model 2,
      $queryParameters ? : {},
      $domain ? : string
  }`
  But maybe the issue is on hapi-swagger side ? could you confirm ?

Thanks a lot.

**Comment by dcbrwn** [comment]
Automatic models generation would be really cool. Without this, generated TypeScript client is pretty much useless. Please, indicate in readme that this feature is supported or not.

**Comment by wcandillon** [comment]
@no-more can you check in v1.7.0 if the types are generated as you would like? Feel free to re-open.
