### ISSUE TITLE
Add CLI?

### ISSUE THREAD

**Issue by swashcap** [wcandillon/swagger-js-codegen#146]
Your project looks super awesome! It would be neat to have a CLI so codegen could be called through an npm script or likewise. I’d be interested in contributing if you want!

**Comment by wcandillon** [comment]
@swashcap Yes a PR would be welcomed :)

**Comment by pouyanh** [comment]
@wcandillon @swashcap There already is one: #195

**Comment by phil-warner** [comment]
Can you point to the CLI documentation please?
