### ISSUE TITLE
Support Typescript 'type' template

### ISSUE THREAD

**Issue by bartlomn** [wcandillon/swagger-js-codegen#152]
Given:
```javascript
CodeGen.getTypescriptCode({
     template: {
          class: fs.readFileSync('./my-class.mustache', 'utf-8'),
          method: fs.readFileSync('./my-method.mustache', 'utf-8'),
          type: fs.readFileSync('./my-type.mustache', 'utf-8')
}});
```
Expected:
typescript types are generated using custom `my-type.mustache` template

Actual:
Default templates are used

**Comment by LegNeato** [comment]
This can be closed now due to https://github.com/wcandillon/swagger-js-codegen/commit/941d04e958b0e2c74713a1158e0496a61a046f65 landing, right?
