### ISSUE TITLE
Samples

### ISSUE THREAD

**Issue by bradygaster** [wcandillon/swagger-js-codegen#23]
It'd be great to have samples demonstrating the generated code in HTML pages. I'm having some difficulty wiring up the factories into a single controller. A simple pet store demo would be quite helpful.

**Comment by wcandillon** [comment]
@bradygaster I'm closing this for the moment, keep me posted.

**Comment by bradygaster** [comment]
That definitely does, help, @wcandillon! Thanks for that. I'll peruse the code and try to grok it and may follow up. Sorry for my lag on the issue's response - email filters #ftw.
