### ISSUE TITLE
Generated HTTP method is empty for AngularJS client

### ISSUE THREAD

**Issue by wangjia184** [wcandillon/swagger-js-codegen#24]
I am not sure if this issue exists in generated nodejs code, it does exist for generated AngularJS when swagger spec JSON is loaded from [ServiceStack's Swagger API](https://github.com/ServiceStack/ServiceStack/wiki/Swagger-API). 

            var method = {
                path: api.path,
                className: opts.className,
                methodName: op.nickname,
                method: op.method,
                isGET: op.method === 'GET',
                summary: op.summary,
                parameters: op.parameters
            };

should be fixed to

            var method = {
                path: api.path,
                className: opts.className,
                methodName: op.nickname,
                method: op.method || op.httpMethod,
                isGET: (op.method || op.httpMethod) === 'GET',
                summary: op.summary,
                parameters: op.parameters
            };

**Comment by wcandillon** [comment]
`httpMethod` doesn't appear to be a valid property name. I couldn't find it in swagger 1.0 or 2.0 specs.

**Comment by wangjia184** [comment]
I know, but that is what it actually responsed from ServiceStack's Swagger extension.
please could you add that as a fallback support

**Comment by wcandillon** [comment]
@wangjia184 You can simply process the JSON file to conform to the swagger spec before feeding it to the swagger codegen. Does it make sense?

**Comment by wangjia184** [comment]
well, I can't find a way to correct the JSON spec on server side as ServiceStack wraps it without any inspect channce.   To correct the JSON in client side is not a problem for me.  but it will be a problem for the developers who call my REST interface. -- they may not be aware of this problem and encounter the same issue as I did when I first time try your lovely library :)
