### ISSUE TITLE
Use Angular's $resource service

### ISSUE THREAD

**Issue by wking** [wcandillon/swagger-js-codegen#27]
The current generated code uses `$q` and `$http` directly, but it seems like it would be easier to take advantage of the existing [`$resource` service][1] to setup the Angular bindings.  Thoughts?

[1]: https://docs.angularjs.org/api/ngResource/service/$resource

**Comment by wcandillon** [comment]
@wking I'm closing the issue for now but PRs are definitely welcome. Also if the current setup has limitations that I do not foresee, please let me know.
