### ISSUE TITLE
use bracket notation when accessing the parameters object which passed by the user

### ISSUE THREAD

**Issue by borisirota** [wcandillon/swagger-js-codegen#47]
[this check](https://github.com/wcandillon/swagger-js-codegen/blob/master/templates/method.mustache#L55) and [this check](https://github.com/wcandillon/swagger-js-codegen/blob/master/templates/method.mustache#L62) uses the dot notation on the parameters object which passed by the user and can contain keys like "this-is-key"

Boris

**Comment by wcandillon** [comment]
@borisirota ho boy, nice catch!

**Comment by borisirota** [comment]
:+1:
