### ISSUE TITLE
Link to the gulp task is dead

### ISSUE THREAD

**Issue by AndreSteenveld** [wcandillon/swagger-js-codegen#84]
The link in the readme pointing to the example gulp task is dead. There is a fork of the project though and the (same?) task can be found here. https://github.com/wcandillon/cellstore/blob/master/tasks/swagger.js

**Comment by wcandillon** [comment]
@AndreSteenveld thanks for pointing that out. :+1:

**Comment by dave-irvine** [comment]
Looks like the new link is dead also.
